// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.kzhou.protobuf;

public final class DataInfo {
  private DataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kzhou.protobuf.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>optional string address = 3;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 3;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 3;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
     * @return Whether the idCard field is set.
     */
    boolean hasIdCard();
    /**
     * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
     * @return The idCard.
     */
    com.kzhou.protobuf.DataInfo.Student.IdCard getIdCard();
    /**
     * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
     */
    com.kzhou.protobuf.DataInfo.Student.IdCardOrBuilder getIdCardOrBuilder();

    /**
     * <code>optional .com.kzhou.protobuf.Student.PhoneType type = 5 [default = HOME];</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional .com.kzhou.protobuf.Student.PhoneType type = 5 [default = HOME];</code>
     * @return The type.
     */
    com.kzhou.protobuf.DataInfo.Student.PhoneType getType();
  }
  /**
   * Protobuf type {@code com.kzhou.protobuf.Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kzhou.protobuf.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      address_ = "";
      type_ = 1;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              address_ = bs;
              break;
            }
            case 34: {
              com.kzhou.protobuf.DataInfo.Student.IdCard.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) != 0)) {
                subBuilder = idCard_.toBuilder();
              }
              idCard_ = input.readMessage(com.kzhou.protobuf.DataInfo.Student.IdCard.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(idCard_);
                idCard_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.kzhou.protobuf.DataInfo.Student.PhoneType value = com.kzhou.protobuf.DataInfo.Student.PhoneType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                type_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kzhou.protobuf.DataInfo.internal_static_com_kzhou_protobuf_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kzhou.protobuf.DataInfo.internal_static_com_kzhou_protobuf_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kzhou.protobuf.DataInfo.Student.class, com.kzhou.protobuf.DataInfo.Student.Builder.class);
    }

    /**
     * Protobuf enum {@code com.kzhou.protobuf.Student.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.kzhou.protobuf.DataInfo.Student.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.kzhou.protobuf.Student.PhoneType)
    }

    public interface IdCardOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.kzhou.protobuf.Student.IdCard)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string idNumber = 1;</code>
       * @return Whether the idNumber field is set.
       */
      boolean hasIdNumber();
      /**
       * <code>required string idNumber = 1;</code>
       * @return The idNumber.
       */
      java.lang.String getIdNumber();
      /**
       * <code>required string idNumber = 1;</code>
       * @return The bytes for idNumber.
       */
      com.google.protobuf.ByteString
          getIdNumberBytes();

      /**
       * <code>required string idType = 2;</code>
       * @return Whether the idType field is set.
       */
      boolean hasIdType();
      /**
       * <code>required string idType = 2;</code>
       * @return The idType.
       */
      java.lang.String getIdType();
      /**
       * <code>required string idType = 2;</code>
       * @return The bytes for idType.
       */
      com.google.protobuf.ByteString
          getIdTypeBytes();
    }
    /**
     * Protobuf type {@code com.kzhou.protobuf.Student.IdCard}
     */
    public static final class IdCard extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.kzhou.protobuf.Student.IdCard)
        IdCardOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use IdCard.newBuilder() to construct.
      private IdCard(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private IdCard() {
        idNumber_ = "";
        idType_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new IdCard();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private IdCard(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                idNumber_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                idType_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kzhou.protobuf.DataInfo.internal_static_com_kzhou_protobuf_Student_IdCard_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kzhou.protobuf.DataInfo.internal_static_com_kzhou_protobuf_Student_IdCard_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kzhou.protobuf.DataInfo.Student.IdCard.class, com.kzhou.protobuf.DataInfo.Student.IdCard.Builder.class);
      }

      private int bitField0_;
      public static final int IDNUMBER_FIELD_NUMBER = 1;
      private volatile java.lang.Object idNumber_;
      /**
       * <code>required string idNumber = 1;</code>
       * @return Whether the idNumber field is set.
       */
      @java.lang.Override
      public boolean hasIdNumber() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string idNumber = 1;</code>
       * @return The idNumber.
       */
      @java.lang.Override
      public java.lang.String getIdNumber() {
        java.lang.Object ref = idNumber_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            idNumber_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string idNumber = 1;</code>
       * @return The bytes for idNumber.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdNumberBytes() {
        java.lang.Object ref = idNumber_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int IDTYPE_FIELD_NUMBER = 2;
      private volatile java.lang.Object idType_;
      /**
       * <code>required string idType = 2;</code>
       * @return Whether the idType field is set.
       */
      @java.lang.Override
      public boolean hasIdType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string idType = 2;</code>
       * @return The idType.
       */
      @java.lang.Override
      public java.lang.String getIdType() {
        java.lang.Object ref = idType_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            idType_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string idType = 2;</code>
       * @return The bytes for idType.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdTypeBytes() {
        java.lang.Object ref = idType_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasIdNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasIdType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idNumber_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, idType_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idNumber_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, idType_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.kzhou.protobuf.DataInfo.Student.IdCard)) {
          return super.equals(obj);
        }
        com.kzhou.protobuf.DataInfo.Student.IdCard other = (com.kzhou.protobuf.DataInfo.Student.IdCard) obj;

        if (hasIdNumber() != other.hasIdNumber()) return false;
        if (hasIdNumber()) {
          if (!getIdNumber()
              .equals(other.getIdNumber())) return false;
        }
        if (hasIdType() != other.hasIdType()) return false;
        if (hasIdType()) {
          if (!getIdType()
              .equals(other.getIdType())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasIdNumber()) {
          hash = (37 * hash) + IDNUMBER_FIELD_NUMBER;
          hash = (53 * hash) + getIdNumber().hashCode();
        }
        if (hasIdType()) {
          hash = (37 * hash) + IDTYPE_FIELD_NUMBER;
          hash = (53 * hash) + getIdType().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.kzhou.protobuf.DataInfo.Student.IdCard parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.kzhou.protobuf.DataInfo.Student.IdCard prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.kzhou.protobuf.Student.IdCard}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.kzhou.protobuf.Student.IdCard)
          com.kzhou.protobuf.DataInfo.Student.IdCardOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.kzhou.protobuf.DataInfo.internal_static_com_kzhou_protobuf_Student_IdCard_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.kzhou.protobuf.DataInfo.internal_static_com_kzhou_protobuf_Student_IdCard_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.kzhou.protobuf.DataInfo.Student.IdCard.class, com.kzhou.protobuf.DataInfo.Student.IdCard.Builder.class);
        }

        // Construct using com.kzhou.protobuf.DataInfo.Student.IdCard.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          idNumber_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          idType_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.kzhou.protobuf.DataInfo.internal_static_com_kzhou_protobuf_Student_IdCard_descriptor;
        }

        @java.lang.Override
        public com.kzhou.protobuf.DataInfo.Student.IdCard getDefaultInstanceForType() {
          return com.kzhou.protobuf.DataInfo.Student.IdCard.getDefaultInstance();
        }

        @java.lang.Override
        public com.kzhou.protobuf.DataInfo.Student.IdCard build() {
          com.kzhou.protobuf.DataInfo.Student.IdCard result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.kzhou.protobuf.DataInfo.Student.IdCard buildPartial() {
          com.kzhou.protobuf.DataInfo.Student.IdCard result = new com.kzhou.protobuf.DataInfo.Student.IdCard(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.idNumber_ = idNumber_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.idType_ = idType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.kzhou.protobuf.DataInfo.Student.IdCard) {
            return mergeFrom((com.kzhou.protobuf.DataInfo.Student.IdCard)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.kzhou.protobuf.DataInfo.Student.IdCard other) {
          if (other == com.kzhou.protobuf.DataInfo.Student.IdCard.getDefaultInstance()) return this;
          if (other.hasIdNumber()) {
            bitField0_ |= 0x00000001;
            idNumber_ = other.idNumber_;
            onChanged();
          }
          if (other.hasIdType()) {
            bitField0_ |= 0x00000002;
            idType_ = other.idType_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasIdNumber()) {
            return false;
          }
          if (!hasIdType()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.kzhou.protobuf.DataInfo.Student.IdCard parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.kzhou.protobuf.DataInfo.Student.IdCard) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object idNumber_ = "";
        /**
         * <code>required string idNumber = 1;</code>
         * @return Whether the idNumber field is set.
         */
        public boolean hasIdNumber() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string idNumber = 1;</code>
         * @return The idNumber.
         */
        public java.lang.String getIdNumber() {
          java.lang.Object ref = idNumber_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              idNumber_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string idNumber = 1;</code>
         * @return The bytes for idNumber.
         */
        public com.google.protobuf.ByteString
            getIdNumberBytes() {
          java.lang.Object ref = idNumber_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            idNumber_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string idNumber = 1;</code>
         * @param value The idNumber to set.
         * @return This builder for chaining.
         */
        public Builder setIdNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          idNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string idNumber = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearIdNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          idNumber_ = getDefaultInstance().getIdNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required string idNumber = 1;</code>
         * @param value The bytes for idNumber to set.
         * @return This builder for chaining.
         */
        public Builder setIdNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          idNumber_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object idType_ = "";
        /**
         * <code>required string idType = 2;</code>
         * @return Whether the idType field is set.
         */
        public boolean hasIdType() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required string idType = 2;</code>
         * @return The idType.
         */
        public java.lang.String getIdType() {
          java.lang.Object ref = idType_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              idType_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string idType = 2;</code>
         * @return The bytes for idType.
         */
        public com.google.protobuf.ByteString
            getIdTypeBytes() {
          java.lang.Object ref = idType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            idType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string idType = 2;</code>
         * @param value The idType to set.
         * @return This builder for chaining.
         */
        public Builder setIdType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          idType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string idType = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearIdType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          idType_ = getDefaultInstance().getIdType();
          onChanged();
          return this;
        }
        /**
         * <code>required string idType = 2;</code>
         * @param value The bytes for idType to set.
         * @return This builder for chaining.
         */
        public Builder setIdTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          idType_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.kzhou.protobuf.Student.IdCard)
      }

      // @@protoc_insertion_point(class_scope:com.kzhou.protobuf.Student.IdCard)
      private static final com.kzhou.protobuf.DataInfo.Student.IdCard DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.kzhou.protobuf.DataInfo.Student.IdCard();
      }

      public static com.kzhou.protobuf.DataInfo.Student.IdCard getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<IdCard>
          PARSER = new com.google.protobuf.AbstractParser<IdCard>() {
        @java.lang.Override
        public IdCard parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new IdCard(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<IdCard> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<IdCard> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.kzhou.protobuf.DataInfo.Student.IdCard getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    @java.lang.Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 3;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string address = 3;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 3;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDCARD_FIELD_NUMBER = 4;
    private com.kzhou.protobuf.DataInfo.Student.IdCard idCard_;
    /**
     * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
     * @return Whether the idCard field is set.
     */
    @java.lang.Override
    public boolean hasIdCard() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
     * @return The idCard.
     */
    @java.lang.Override
    public com.kzhou.protobuf.DataInfo.Student.IdCard getIdCard() {
      return idCard_ == null ? com.kzhou.protobuf.DataInfo.Student.IdCard.getDefaultInstance() : idCard_;
    }
    /**
     * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
     */
    @java.lang.Override
    public com.kzhou.protobuf.DataInfo.Student.IdCardOrBuilder getIdCardOrBuilder() {
      return idCard_ == null ? com.kzhou.protobuf.DataInfo.Student.IdCard.getDefaultInstance() : idCard_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>optional .com.kzhou.protobuf.Student.PhoneType type = 5 [default = HOME];</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .com.kzhou.protobuf.Student.PhoneType type = 5 [default = HOME];</code>
     * @return The type.
     */
    @java.lang.Override public com.kzhou.protobuf.DataInfo.Student.PhoneType getType() {
      @SuppressWarnings("deprecation")
      com.kzhou.protobuf.DataInfo.Student.PhoneType result = com.kzhou.protobuf.DataInfo.Student.PhoneType.valueOf(type_);
      return result == null ? com.kzhou.protobuf.DataInfo.Student.PhoneType.HOME : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasIdCard()) {
        if (!getIdCard().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getIdCard());
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeEnum(5, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getIdCard());
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kzhou.protobuf.DataInfo.Student)) {
        return super.equals(obj);
      }
      com.kzhou.protobuf.DataInfo.Student other = (com.kzhou.protobuf.DataInfo.Student) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (hasIdCard() != other.hasIdCard()) return false;
      if (hasIdCard()) {
        if (!getIdCard()
            .equals(other.getIdCard())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      if (hasIdCard()) {
        hash = (37 * hash) + IDCARD_FIELD_NUMBER;
        hash = (53 * hash) + getIdCard().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kzhou.protobuf.DataInfo.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kzhou.protobuf.DataInfo.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kzhou.protobuf.DataInfo.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kzhou.protobuf.DataInfo.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kzhou.protobuf.DataInfo.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kzhou.protobuf.DataInfo.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kzhou.protobuf.DataInfo.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kzhou.protobuf.DataInfo.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kzhou.protobuf.DataInfo.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kzhou.protobuf.DataInfo.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kzhou.protobuf.DataInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kzhou.protobuf.DataInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kzhou.protobuf.DataInfo.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kzhou.protobuf.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kzhou.protobuf.Student)
        com.kzhou.protobuf.DataInfo.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kzhou.protobuf.DataInfo.internal_static_com_kzhou_protobuf_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kzhou.protobuf.DataInfo.internal_static_com_kzhou_protobuf_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kzhou.protobuf.DataInfo.Student.class, com.kzhou.protobuf.DataInfo.Student.Builder.class);
      }

      // Construct using com.kzhou.protobuf.DataInfo.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIdCardFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (idCardBuilder_ == null) {
          idCard_ = null;
        } else {
          idCardBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kzhou.protobuf.DataInfo.internal_static_com_kzhou_protobuf_Student_descriptor;
      }

      @java.lang.Override
      public com.kzhou.protobuf.DataInfo.Student getDefaultInstanceForType() {
        return com.kzhou.protobuf.DataInfo.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.kzhou.protobuf.DataInfo.Student build() {
        com.kzhou.protobuf.DataInfo.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kzhou.protobuf.DataInfo.Student buildPartial() {
        com.kzhou.protobuf.DataInfo.Student result = new com.kzhou.protobuf.DataInfo.Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (idCardBuilder_ == null) {
            result.idCard_ = idCard_;
          } else {
            result.idCard_ = idCardBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kzhou.protobuf.DataInfo.Student) {
          return mergeFrom((com.kzhou.protobuf.DataInfo.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kzhou.protobuf.DataInfo.Student other) {
        if (other == com.kzhou.protobuf.DataInfo.Student.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000004;
          address_ = other.address_;
          onChanged();
        }
        if (other.hasIdCard()) {
          mergeIdCard(other.getIdCard());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (hasIdCard()) {
          if (!getIdCard().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kzhou.protobuf.DataInfo.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kzhou.protobuf.DataInfo.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       * @return Whether the age field is set.
       */
      @java.lang.Override
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 3;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string address = 3;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }

      private com.kzhou.protobuf.DataInfo.Student.IdCard idCard_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kzhou.protobuf.DataInfo.Student.IdCard, com.kzhou.protobuf.DataInfo.Student.IdCard.Builder, com.kzhou.protobuf.DataInfo.Student.IdCardOrBuilder> idCardBuilder_;
      /**
       * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
       * @return Whether the idCard field is set.
       */
      public boolean hasIdCard() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
       * @return The idCard.
       */
      public com.kzhou.protobuf.DataInfo.Student.IdCard getIdCard() {
        if (idCardBuilder_ == null) {
          return idCard_ == null ? com.kzhou.protobuf.DataInfo.Student.IdCard.getDefaultInstance() : idCard_;
        } else {
          return idCardBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
       */
      public Builder setIdCard(com.kzhou.protobuf.DataInfo.Student.IdCard value) {
        if (idCardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          idCard_ = value;
          onChanged();
        } else {
          idCardBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
       */
      public Builder setIdCard(
          com.kzhou.protobuf.DataInfo.Student.IdCard.Builder builderForValue) {
        if (idCardBuilder_ == null) {
          idCard_ = builderForValue.build();
          onChanged();
        } else {
          idCardBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
       */
      public Builder mergeIdCard(com.kzhou.protobuf.DataInfo.Student.IdCard value) {
        if (idCardBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              idCard_ != null &&
              idCard_ != com.kzhou.protobuf.DataInfo.Student.IdCard.getDefaultInstance()) {
            idCard_ =
              com.kzhou.protobuf.DataInfo.Student.IdCard.newBuilder(idCard_).mergeFrom(value).buildPartial();
          } else {
            idCard_ = value;
          }
          onChanged();
        } else {
          idCardBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
       */
      public Builder clearIdCard() {
        if (idCardBuilder_ == null) {
          idCard_ = null;
          onChanged();
        } else {
          idCardBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
       */
      public com.kzhou.protobuf.DataInfo.Student.IdCard.Builder getIdCardBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getIdCardFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
       */
      public com.kzhou.protobuf.DataInfo.Student.IdCardOrBuilder getIdCardOrBuilder() {
        if (idCardBuilder_ != null) {
          return idCardBuilder_.getMessageOrBuilder();
        } else {
          return idCard_ == null ?
              com.kzhou.protobuf.DataInfo.Student.IdCard.getDefaultInstance() : idCard_;
        }
      }
      /**
       * <code>optional .com.kzhou.protobuf.Student.IdCard idCard = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kzhou.protobuf.DataInfo.Student.IdCard, com.kzhou.protobuf.DataInfo.Student.IdCard.Builder, com.kzhou.protobuf.DataInfo.Student.IdCardOrBuilder> 
          getIdCardFieldBuilder() {
        if (idCardBuilder_ == null) {
          idCardBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kzhou.protobuf.DataInfo.Student.IdCard, com.kzhou.protobuf.DataInfo.Student.IdCard.Builder, com.kzhou.protobuf.DataInfo.Student.IdCardOrBuilder>(
                  getIdCard(),
                  getParentForChildren(),
                  isClean());
          idCard_ = null;
        }
        return idCardBuilder_;
      }

      private int type_ = 1;
      /**
       * <code>optional .com.kzhou.protobuf.Student.PhoneType type = 5 [default = HOME];</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional .com.kzhou.protobuf.Student.PhoneType type = 5 [default = HOME];</code>
       * @return The type.
       */
      @java.lang.Override
      public com.kzhou.protobuf.DataInfo.Student.PhoneType getType() {
        @SuppressWarnings("deprecation")
        com.kzhou.protobuf.DataInfo.Student.PhoneType result = com.kzhou.protobuf.DataInfo.Student.PhoneType.valueOf(type_);
        return result == null ? com.kzhou.protobuf.DataInfo.Student.PhoneType.HOME : result;
      }
      /**
       * <code>optional .com.kzhou.protobuf.Student.PhoneType type = 5 [default = HOME];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.kzhou.protobuf.DataInfo.Student.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.kzhou.protobuf.Student.PhoneType type = 5 [default = HOME];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 1;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.kzhou.protobuf.Student)
    }

    // @@protoc_insertion_point(class_scope:com.kzhou.protobuf.Student)
    private static final com.kzhou.protobuf.DataInfo.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kzhou.protobuf.DataInfo.Student();
    }

    public static com.kzhou.protobuf.DataInfo.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kzhou.protobuf.DataInfo.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kzhou_protobuf_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kzhou_protobuf_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kzhou_protobuf_Student_IdCard_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kzhou_protobuf_Student_IdCard_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\022com.kzhou.protobuf\"\375\001\n\007" +
      "Student\022\014\n\004name\030\001 \002(\t\022\013\n\003age\030\002 \001(\005\022\017\n\007ad" +
      "dress\030\003 \001(\t\0222\n\006idCard\030\004 \001(\0132\".com.kzhou." +
      "protobuf.Student.IdCard\0229\n\004type\030\005 \001(\0162%." +
      "com.kzhou.protobuf.Student.PhoneType:\004HO" +
      "ME\032*\n\006IdCard\022\020\n\010idNumber\030\001 \002(\t\022\016\n\006idType" +
      "\030\002 \002(\t\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020" +
      "\001\022\010\n\004WORK\020\002B \n\022com.kzhou.protobufB\010DataI" +
      "nfoH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_kzhou_protobuf_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kzhou_protobuf_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kzhou_protobuf_Student_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", "IdCard", "Type", });
    internal_static_com_kzhou_protobuf_Student_IdCard_descriptor =
      internal_static_com_kzhou_protobuf_Student_descriptor.getNestedTypes().get(0);
    internal_static_com_kzhou_protobuf_Student_IdCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kzhou_protobuf_Student_IdCard_descriptor,
        new java.lang.String[] { "IdNumber", "IdType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
